### ISSUE TITLE
[Dashing compile error] dds_PublisherQoS_finalize was not declared

### ISSUE THREAD

**Issue by kteriusghub** [ros2/rmw_gurumdds#5]
I received the latest tag (0.7.4) of Dashing branch, and tried to build the ROS2.
And then, there were many compile error of 'dds_PublisherQoS_finalize was not declared in this scope'.
I found that the 'dds_PublisherQoS_finalize' was mainly added to the 0.7.4.
Please, check this issue and suggest the solution.

**Comment by clemjh** [comment]
The latest version (0.7.4) of `rmw_gurumdds_cpp` requires the latest version (2.5.1861) of GurumDDS, which was released as trial a few minutes ago. You can try downloading GurumDDS again or use version 0.7.3 of `rmw_gurumdds_cpp` instead.
I apologize for the inconvenience. Thank you for using our RMW.

**Comment by kteriusghub** [comment]
Please, describe the properly paired version to the README.md.
And, if the library version gives the same impact to rosidl_typesupport_gurumdds, please, give the information to it.
Thanks
